# Generated by Django 5.1.1 on 2025-09-21 03:41

import django.db.models.deletion
import product.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('product', '0004_alter_wishlist_unique_together_wishlist_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=product.models.default_expiry)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='product.wishlist')),
            ],
        ),
    ]
